INSERT INTO `grabfreshfood`.`reviews` (`id`, `comment`, `product_id`, `rating`, `user_id`, `username`) VALUES
(6, 'Reasonably priced and tasty.', '2', '4', '1', 'Mei Ling Tan'),
(7, 'Decent for the price.', '2', '3', '2', 'Kumar Ramasamy'),
(8, 'Expected more sweetness, but edible.', '2', '3', '3', 'Ah Meng Lim'),
(9, 'Expected more sweetness, but edible.', '2', '3', '4', 'Siti Abdul'),
(10, 'Perfect for hot weather. So refreshing!', '2', '5', '5', 'Jia Wei Lee'),
(11, 'Won’t buy this again. Waste of money.', '2', '1', '6', 'Anand Pillai'),
(12, 'Sweet and good size, though a bit soft.', '2', '4', '7', 'Xin Yi Wong'),
(13, 'Delivery was fine but the fruit wasn’t fresh.', '2', '2', '8', 'Aisha Rahman'),
(14, 'Great value and juicy – highly recommended!', '2', '5', '9', 'Chun Kit Ng'),
(15, 'Nice taste and quality overall.', '2', '4', '10', 'Divya Nair'),
(16, 'Fresh and delicious – one of the best I\'ve had.', '2', '5', '11', 'Kai Xuan Tan'),
(17, 'Expected more sweetness, but edible.', '2', '3', '12', 'Faridah Yusof'),
(18, 'Could be better – looks nice but bland taste.', '2', '2', '13', 'Min Hui Chua'),
(19, 'Great value and juicy – highly recommended!', '2', '5', '14', 'Kenji Yamamoto'),
(20, 'Average quality, not too sweet.', '2', '3', '15', 'Zara Abdullah'),
(21, 'Nice taste and quality overall.', '2', '4', '16', 'Zhi Hao Tay'),
(22, 'Absolutely loved the honey dew! Super sweet and fresh.', '2', '5', '17', 'Rachel Teo'),
(23, 'Expected more sweetness, but edible.', '2', '3', '18', 'Arvind Narayanan'),
(24, 'Reasonably priced and tasty.', '2', '4', '19', 'Melissa Chan'),
(25, 'Mushy, tasteless, and overripe.', '2', '1', '20', 'Gerald Goh'),
(26, 'Very disappointed, it was rotten inside.', '2', '1', '21', 'Hui Ying Tan'),
(27, 'Fresh and delicious – one of the best I\'ve had.', '2', '5', '22', 'Liang Yi Soh'),
(28, 'Average quality, not too sweet.', '2', '3', '23', 'Samantha Neo'),
(29, 'It was okay, not bad but not great.', '2', '3', '24', 'David Tan'),
(30, 'Too ripe and mushy for my liking.', '2', '2', '25', 'Fadzil Ahmad'),
(31, 'Very satisfied, will buy again!', '2', '5', '26', 'Angela Lim'),
(32, 'Could be better – looks nice but bland taste.', '2', '2', '27', 'Yong Sheng Koh'),
(33, 'Pretty fresh and came on time.', '2', '4', '28', 'Nora Binte Ali'),
(34, 'Slightly underripe, but acceptable.', '2', '3', '29', 'Jun Jie Lee'),
(35, 'Absolutely loved the honey dew! Super sweet and fresh.', '2', '5', '30', 'Charlene Toh'),
(36, 'Not as good as I expected.', '2', '2', '31', 'Ramesh Das'),
(37, 'Great value and juicy – highly recommended!', '2', '5', '32', 'Clarissa Yeo'),
(38, 'Expected more sweetness, but edible.', '2', '3', '33', 'Michael Yip'),
(39, 'Not sweet enough and had bruises.', '2', '2', '34', 'Hannah Tan'),
(40, 'Very sweet and big in size. Will buy again!', '2', '5', '35', 'Amelia Ong'),
(41, 'Nice taste and quality overall.', '2', '4', '36', 'Imran Ibrahim'),
(42, 'Too ripe and mushy for my liking.', '2', '2', '37', 'Soo Mei Lai'),
(43, 'Not as good as I expected.', '2', '2', '38', 'Kelvin Ng'),
(44, 'Delivery was fine but the fruit wasn’t fresh.', '2', '2', '39', 'Yuki Tanaka'),
(45, 'Great value and juicy – highly recommended!', '2', '5', '40', 'Tharman Ramasamy'),
(46, 'Very disappointed, it was rotten inside.', '2', '1', '41', 'Serena Choo'),
(47, 'Fresh and delicious – one of the best I\'ve had.', '2', '5', '42', 'Rafiq Osman'),
(48, 'Sweet and good size, though a bit soft.', '2', '4', '43', 'Karen Low'),
(49, 'Expected more sweetness, but edible.', '2', '3', '44', 'Taufik Jamal'),
(50, 'Very satisfied, will buy again!', '2', '5', '45', 'Liyana Zulkifli'),
(51, 'Not fresh at all – had to throw it away.', '2', '1', '46', 'Ben Ho'),
(52, 'Average quality, not too sweet.', '2', '3', '47', 'Wendy Tng'),
(53, 'Very sweet and big in size. Will buy again!', '2', '5', '48', 'Marcus Quek'),
(54, 'Slightly underripe, but acceptable.', '2', '3', '49', 'Fatimah Ali'),
(55, 'Great value and juicy – highly recommended!', '2', '5', '50', 'Stanley Lau');
